export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#070b14] text-white py-20 px-4">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        <p className="text-slate-400 mb-4">Last updated: July 2026</p>

        <h2 className="text-xl font-semibold mt-8 mb-3">1. Acceptance of Terms</h2>
        <p className="text-slate-300 mb-4">
          By using CareerMate, you agree to these terms. If you do not agree, do not use the service.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">2. Description of Service</h2>
        <p className="text-slate-300 mb-4">
          CareerMate provides AI-powered career counseling and guidance tailored to the Pakistani job market. 
          Our service includes career assessments, personalized reports, monthly action plans, daily journaling, 
          and streak tracking.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">3. User Accounts</h2>
        <p className="text-slate-300 mb-4">
          You are responsible for maintaining the confidentiality of your account credentials. 
          You must provide accurate information during registration. CareerMate reserves the right 
          to suspend or terminate accounts that violate these terms.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">4. Free Tier Limitations</h2>
        <p className="text-slate-300 mb-4">
          CareerMate offers 2 free Deep Dive sessions per week. We reserve the right to modify 
          free tier limitations at any time. Excessive use or abuse of the platform may result 
          in account restrictions.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">5. AI-Generated Content</h2>
        <p className="text-slate-300 mb-4">
          Career recommendations, reports, and guidance are generated by AI models (Google Gemini, Groq). 
          While we strive for accuracy, AI-generated content may contain errors. CareerMate is a 
          guidance tool, not a guarantee of employment or career outcomes. Always verify important 
          information independently.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">6. User Conduct</h2>
        <p className="text-slate-300 mb-4">
          You agree not to misuse the service, including but not limited to: attempting to break 
          security measures, using automated tools to access the platform, submitting false information, 
          or using the service for any illegal purpose.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">7. Intellectual Property</h2>
        <p className="text-slate-300 mb-4">
          CareerMate, its branding, and proprietary technology are owned by CareerMate. 
          Career reports generated for you are yours to keep and use personally.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">8. Limitation of Liability</h2>
        <p className="text-slate-300 mb-4">
          CareerMate is provided "as is" without warranties. We are not liable for any damages 
          arising from your use of the service, including career decisions made based on AI guidance.
        </p>

        <h2 className="text-xl font-semibold mt-8 mb-3">9. Contact</h2>
        <p className="text-slate-300 mb-4">
          For questions about these terms, contact: hanzala78616@gmail.com
        </p>
      </div>
    </div>
  )
}